//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelStationProgram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuelStationProgram.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Customers](
        ///	[ID] [uniqueidentifier] NOT NULL,
        ///	[Name] [varchar](40) NOT NULL,
        ///	[Surname] [varchar](40) NOT NULL,
        ///	[CardNumber] [int] NOT NULL
        ///)
        ///.
        /// </summary>
        internal static string CreateCustomers {
            get {
                return ResourceManager.GetString("CreateCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE [dbo].[Employees](
        ///	[ID] [uniqueidentifier] NOT NULL,
        ///	[Name] [varchar](40) NOT NULL,
        ///	[Surname] [varchar](40) NOT NULL,
        ///	[DateStart] [date] NOT NULL,
        ///	[DateEnd] [date] NOT NULL,
        ///	[Salary] [decimal](18,2) NOT NULL
        ///)
        ///.
        /// </summary>
        internal static string CreateEmployees {
            get {
                return ResourceManager.GetString("CreateEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE [dbo].[Items](
        ///	[ID] [uniqueidentifier] NOT NULL,
        ///	[Code] [nvarchar](40) NOT NULL,
        ///	[Description] [nvarchar](255) NOT NULL,
        ///	[ItemType] [nvarchar](40) NOT NULL,
        ///	[Price] [decimal](18, 2) NOT NULL,
        ///	[Cost] [decimal](18, 2) NOT NULL
        ///).
        /// </summary>
        internal static string CreateItems {
            get {
                return ResourceManager.GetString("CreateItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE [dbo].[Transactions](
        ///    [ID] [uniqueidentifier] NOT NULL,
        ///    [Date] [date] NOT NULL,
        ///    [CustomerID] [uniqueidentifier] NOT NULL,
        ///	[DiscountValue] [decimal](18, 2) NOT NULL,
        ///	[TotalValue] [decimal](18, 2) NOT NULL
        ///)
        ///
        ///CREATE TABLE [dbo].[TransactionLines](
        ///    [ID] [uniqueidentifier] NOT NULL,
        ///    [TransactionID] [uniqueidentifier] NOT NULL,
        ///    [ItemID] [uniqueidentifier] NOT NULL,
        ///    Quantity [int] NOT NULL,
        ///	[ItemPrice] [decimal](18, 2) NOT NULL,
        ///	[Value] [decimal](18, 2) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTransactions {
            get {
                return ResourceManager.GetString("CreateTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Customers]
        ///           ([ID]
        ///           ,[Name]
        ///           ,[Surname]
        ///           ,[CardNumber])
        ///     VALUES
        ///           (@ID,
        ///           @Name,
        ///           @Surname,
        ///           @CardNumber).
        /// </summary>
        internal static string InsertCustomer {
            get {
                return ResourceManager.GetString("InsertCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Employees]
        ///           ([ID]
        ///           ,[Name]
        ///           ,[Surname]
        ///           ,[DateStart]
        ///           ,[DateEnd]
        ///           ,[Salary])
        ///     VALUES
        ///           (@ID,
        ///           @Name,
        ///           @Surname,
        ///           @DateStart,
        ///           @DateEnd,
        ///           @Salary)
        ///.
        /// </summary>
        internal static string InsertEmployee {
            get {
                return ResourceManager.GetString("InsertEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Items]
        ///           ([ID]
        ///           ,[Code]
        ///           ,[Description]
        ///           ,[ItemType]
        ///           ,[Price]
        ///           ,[Cost])
        ///     VALUES
        ///           (@ID,
        ///           @Code,
        ///           @Description,
        ///           @ItemType,
        ///           @Price,
        ///           @Cost)
        ///.
        /// </summary>
        internal static string InsertItem {
            get {
                return ResourceManager.GetString("InsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[Customers].
        /// </summary>
        internal static string SelectCustomers {
            get {
                return ResourceManager.GetString("SelectCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[Employees].
        /// </summary>
        internal static string SelectEmployees {
            get {
                return ResourceManager.GetString("SelectEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[Items].
        /// </summary>
        internal static string SelectItems {
            get {
                return ResourceManager.GetString("SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[Transactions].
        /// </summary>
        internal static string SelectTransactions {
            get {
                return ResourceManager.GetString("SelectTransactions", resourceCulture);
            }
        }
    }
}
